# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "CHANGE_ME"
primary_region = "ams"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  processes = ["app"]
